### ISSUE TITLE
Overspawning of Lanterns from Mowzie Mobs in Forest Biomes

### ISSUE THREAD

**Issue by BugmanBugman** [GreatOrator/TolkienTweaks-Mobs-Edition#22]
## Description
When you enter one of the roofed forests like Lothlorien, Mowzie Mobs Lanterns spawn like crazy. Not sure if it's this mod or Mowzies.

## Base information
* Minecraft version:
* Minecraft Forge version:1.12.2-forge1.12.2-14.23.5.2847
* TolkienTweaks-Mobs version:  TolkienMobs-1.12.2-1.12.30.37.0-universal

## Crash report
![2020-03-14_17 18 16](https://user-images.githubusercontent.com/40730042/76691962-5a676900-661e-11ea-863b-184ecf28e921.png)
![2020-03-14_17 18 12](https://user-images.githubusercontent.com/40730042/76691997-9f8b9b00-661e-11ea-9d1b-02a740bd3128.png)

**Comment by GreatOrator** [comment]
Honestly, my mod does nothing to any mobs other than ones I made so it would be mowzies spawn requirements causing this.
